server:
  port: 8080
  servlet:
    context-path: /bootcamp
spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: postgres://epqlreimoyojnk:86f94631fa719b98aac362d2a9f2b7df72a7715308db2db1ae1afd87fc1c47a5@ec2-54-243-92-68.compute-1.amazonaws.com:5432/d6lhkct59v3s7q
    username: epqlreimoyojnk
    password: 86f94631fa719b98aac362d2a9f2b7df72a7715308db2db1ae1afd87fc1c47a5
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    #database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    #open-in-view: false
    generate-ddl: true #gerar bd automaticamente

application:
  description: Projeto criado para o santander DIO - Santander